### ISSUE TITLE
[Bug]: Keyboard input no longer working

### ISSUE THREAD

**Issue by baioc** [snapcrafters/mattermost-desktop#105]
### What happened?

The app does not respond to keyboard inputs (e.g. typing on the message field).
Mouse clicks still work and the rest of the client is responsive in general.

After finding [this older issue with firejailed Firefox](https://askubuntu.com/questions/972693/no-text-entry-or-keyboard-capabilities-in-firefox-browser-when-running-in-fireja), I tried applying the `GTK_IM_MODULE` env var and it solved the problem:

- If running from the terminal:
    ```sh
    GTK_IM_MODULE=xim mattermost-desktop
    ```
- If running from a desktop menu/launcher:
    ```sh
    cp /var/lib/snapd/desktop/applications/mattermost-desktop_mattermost-desktop.desktop ~/.local/share/applications/
    sed -i 's#Exec=env #Exec=env GTK_IM_MODULE=xim #g' ~/.local/share/applications/mattermost-desktop_mattermost-desktop.desktop
    ```

### What should have happened?

The app should respond to keyboard inputs (e.g. typing on the message field).

### Output of `snap info $snap_name`

```shell
name:      mattermost-desktop
summary:   A secure, flexible platform build for the new era of collaboration
publisher: Snapcrafters*
store-url: https://snapcraft.io/mattermost-desktop
contact:   https://github.com/snapcrafters/mattermost-desktop/issues
license:   MIT
description: |
  Mattermost is secure workplace messaging from behind your firewall.
  
  - Discuss topics in private groups, one-to-one or team-wide
  - Easily share and view image files
  - Connect in-house systems with webhooks and Slack-compatible integrations
  
  For technical and operations teams who execute high-stakes, collaborative
  workflows,
  Mattermost provides integrated team messaging, audio and screen share,
  workflow automation
  and project management. Governments, banks and tech giants use our secure
  collaboration platform
  to reduce risk and error rates while accelerating technical productivity.
  
  To use this app, you need a URL for a Mattermost server.
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - mattermost-desktop
snap-id:      ed0pxJoDHrgmAWHH7baX5nryAHy1UNj0
tracking:     latest/stable
refresh-date: 3 days ago, at 00:50 -03
channels:
  latest/stable:    5.8.1 2024-06-14 (756) 117MB -
  latest/candidate: 5.8.1 2024-06-14 (756) 117MB -
  latest/beta:      ^                            
  latest/edge:      ^                            
installed:          5.8.1            (756) 117MB -
```

### Output of `snap connections $snap_name`

```shell
Interface               Plug                                       Slot                            Notes
audio-playback          mattermost-desktop:audio-playback          :audio-playback                 -
audio-record            mattermost-desktop:audio-record            -                               -
camera                  mattermost-desktop:camera                  -                               -
content[gnome-42-2204]  mattermost-desktop:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   mattermost-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    mattermost-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   mattermost-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 mattermost-desktop:desktop                 :desktop                        -
desktop-legacy          mattermost-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               mattermost-desktop:gsettings               :gsettings                      -
home                    mattermost-desktop:home                    :home                           -
login-session-observe   mattermost-desktop:login-session-observe   -                               -
network                 mattermost-desktop:network                 :network                        -
network-bind            mattermost-desktop:network-bind            :network-bind                   -
opengl                  mattermost-desktop:opengl                  :opengl                         -
pulseaudio              mattermost-desktop:pulseaudio              :pulseaudio                     -
removable-media         mattermost-desktop:removable-media         -                               -
screen-inhibit-control  mattermost-desktop:screen-inhibit-control  :screen-inhibit-control         -
shared-memory           mattermost-desktop:shmem                   :shared-memory                  -
unity7                  mattermost-desktop:unity7                  :unity7                         -
wayland                 mattermost-desktop:wayland                 :wayland                        -
x11                     mattermost-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
snap    2.63+24.04
snapd   2.63+24.04
series  16
ubuntu  24.04
kernel  6.8.0-35-generic
```

### Relevant log output

```shell
Jun 18 12:11:32 workstation gnome-shell[3093]: Window manager warning: last_focus_time (6571401) is greater than comparison timestamp (6571387).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Jun 18 12:11:32 workstation gnome-shell[3093]: Window manager warning: last_user_time (6571401) is greater than comparison timestamp (6571387).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Jun 18 12:11:32 workstation gnome-shell[3093]: Window manager warning: 0x2c00004 appears to be one of the offending windows with a timestamp of 6571401.  Working around...
Jun 18 12:11:35 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:35 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:35 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:35 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:35 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:36 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:36 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:36 workstation mattermost-desk[68266]: Events queue growing too big, will start to drop.
Jun 18 12:11:42 workstation kernel: audit: type=1326 audit(1718723502.674:877): auid=1000 uid=1000 gid=1000 ses=2 subj=snap.mattermost-desktop.mattermost-desktop pid=68266 comm="ThreadPoolSingl" exe="/snap/mattermost-desktop/756/opt/Mattermost/mattermost-desktop" sig=0 arch=c000003e syscall=141 compat=0 ip=0x7b06e0d9278b code=0x50000
Jun 18 12:11:44 workstation systemd[2204]: snap.mattermost-desktop.mattermost-desktop-edaf82a4-40c8-40e3-8d9c-4b153a754dfa.scope: Consumed 25.369s CPU time.
```

### Teminal output of app

```shell
15:29:38.492 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/snap/mattermost-desktop/756/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at bindings (/snap/mattermost-desktop/756/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/snap/mattermost-desktop/756/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
15:29:38.659 › [App.Initialize] Current working directory is /home/baioc, changing into /snap/mattermost-desktop/756/opt/Mattermost
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "mattermost" setting to invalid value "Mattermost.Desktop"
Gtk-Message: 15:29:38.702: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(mattermost-desktop:179734): Gtk-WARNING **: 15:29:38.813: GTK+ module /snap/mattermost-desktop/756/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 15:29:38.813: Failed to load module "canberra-gtk-module"

(mattermost-desktop:179734): Gtk-WARNING **: 15:29:38.817: GTK+ module /snap/mattermost-desktop/756/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 15:29:38.817: Failed to load module "canberra-gtk-module"
[179734:0618/152938.864017:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179838: Permission denied (13)
15:29:38.867 › [App.Config] config.autostart has been configured: false
15:29:38.897 › [App.Initialize] Autoupgrade disabled: false
[179734:0618/152939.029151:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179872: Permission denied (13)
[179734:0618/152939.032031:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179873: Permission denied (13)
[179734:0618/152939.039070:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179879: Permission denied (13)
15:29:39.041 › [ServerDropdownView] init
[179734:0618/152939.046478:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179886: Permission denied (13)
[179734:0618/152939.052882:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179892: Permission denied (13)
[179734:0618/152939.058945:ERROR:zygote_host_impl_linux.cc(274)] Failed to adjust OOM score of renderer with pid 179899: Permission denied (13)
15:29:39.105 › [i18nManager] Failed to set new language en-US
15:29:39.106 › [i18nManager] Failed to set new language US
15:29:39.353 › [App.Config] config.autostart has been configured: false

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:40.763: Unable to connect to ibus: Could not connect: No such file or directory
15:29:40.782 › [App.Config] config.autostart has been configured: false

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:47.986: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.033: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.122: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.169: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.274: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.313: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.442: Events queue growing too big, will start to drop.

(mattermost-desktop:179734): IBUS-WARNING **: 15:29:48.505: Events queue growing too big, will start to drop.
```

**Comment by baioc** [comment]
Actually, I've realized this buggy behavior doesn't apply only to mattermost-desktop, but also other apps such as Evince.

According to [this forum thread](https://forum.snapcraft.io/t/lost-keyboard-input-to-all-x-client-based-snaps-permission-denied/35914/2), this is caused by having one's `~/.cache` dir be a symlink (which was my case as well). As a result, an alternative fix would be to delete that symlink and create a real directory.

I'll close this issue since the actual bug is [elsewhere](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/2026758).
